printWidth: 90
singleQuote: true
trailingComma: es5
useTabs: true
arrowParens: always
plugins:
  - prettier-plugin-svelte
svelteSortOrder: scripts-options-markup-styles
svelteStrictMode: false
svelteAllowShorthand: true
svelteIndentScriptAndStyle: true
